name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: docker login on ghcr.io
        env:
          AT: ${{ secrets.AT }}
          VER: $(date +%s)
        run: docker login ghcr.io -u code-theft-auto -p $AT
      - name: pull python:3.10.4-slim
        run: docker pull python:3.10.4-slim
      - name: docker build
        run: docker build . -t ghcr.io/code-theft-auto/sockeypy:$VER
      - name: docker push
        run: docker push ghcr.io/code-theft-auto/sockeypy:$VER
